fixtures:
  repositories:
    "stdlib":
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "3.0.0"
    "wget":
      repo: "git://github.com/maestrodev/puppet-wget.git"
      ref: "v1.2.2"
  symlinks:
    "selenium": "#{source_dir}"
